// models/History.js
// Mongoose schema for storing user analysis history

const mongoose = require('mongoose');

const historySchema = new mongoose.Schema(
  {
    // Reference to the user who performed this check
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },

    // The input type: 'text' or 'url'
    inputType: {
      type: String,
      enum: ['text', 'url'],
      default: 'text',
    },

    // Original input content (text snippet or URL)
    content: {
      type: String,
      required: true,
      maxlength: [5000, 'Content cannot exceed 5000 characters'],
    },

    // URL if input was a URL
    sourceUrl: {
      type: String,
      default: null,
    },

    // ML model prediction result
    prediction: {
      type: String,
      enum: ['FAKE', 'REAL'],
      required: true,
    },

    // Confidence score from the ML model (0–100)
    confidence: {
      type: Number,
      required: true,
      min: 0,
      max: 100,
    },

    // Short explanation generated by the model
    explanation: {
      type: String,
      default: '',
    },

    // Suspicious words flagged by the model
    suspiciousWords: {
      type: [String],
      default: [],
    },

    // Category classification (optional, e.g., politics, health, etc.)
    category: {
      type: String,
      default: 'General',
    },
  },
  {
    timestamps: true, // createdAt used for weekly activity graphs
  }
);

// Index for efficient user-specific queries
historySchema.index({ user: 1, createdAt: -1 });

module.exports = mongoose.model('History', historySchema);